<?php
declare (strict_types = 1);

namespace app\api\controller;

use app\common\controller\ApiController;
use think\Request;
use app\admin\model\Card as CardModel;
use app\admin\model\UserCardSupport;
use app\admin\model\UserCardHistory;
use app\admin\model\UserCardCall;
use app\admin\model\UserCardShare;

class Card extends ApiController
{
    protected array $noNeedLogin = ['read'];

    /**
     * 模型
     * @var null
     */
    protected $model = null;

    public function initialize():void
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->model = CardModel::class;
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $cid = $this->params['cid'] ?? 0;
        $page = $this->params['page'] ?? 1;
        $limit = $this->params['limit'] ?? 10;
        $title = $this->params['title'] ?? '';
        $where = [
            ['status', '=', 1],
        ];

        if ($title !== '') {
            $where[] = ['title', 'like', '%' . $title . '%'];
        }

        if ($cid > 0) {
            $where[] = ['cate_id', '=', $cid];
        }

        $this->returnData['code'] = 1;
        $this->returnData['data'] = $this->model::field('id, title, cover_img, create_time, read_count')
            ->where($where)
            ->limit(($page - 1) * $limit, $limit)
            ->order('id', 'desc')
            ->select();
        $this->returnApiData();
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id = 0)
    {
        $this->returnData['code'] = 1;
        if ($id) {
            $this->returnData['data'] = $this->model::withCount(['userCardHistory', 'userCardSupport'])->find($id);
        } else {
            $card = $this->model::withCount(['userCardHistory', 'userCardSupport'])
                ->with(['userCardHistory' => function ($query) {
                    $query->with(['user' => function ($q) {
                        $q->withoutField('password');
                    }]);
                }])
                ->where(['status' => 1])
                ->order('id desc')
                ->limit(1)->select();
            $this->returnData['data'] = $card[0] ?? [];
        }
        $this->returnApiData();
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function setInc(Request $request, $id)
    {
        $params = $request->only(['id', 'share', 'call', 'support']);
        foreach ($params as $key => $val) {
            $model = null;

            if ($key === 'share') {
                $model = new UserCardShare();
            } elseif ($key === 'call') {
                $model = new UserCardCall();
            } elseif ($key === 'support') {
                $model = new UserCardSupport();
            }

            if ($model !== null) {
//                $this->model::where('id', $id)->inc($key)->update();
                $model->save([
                    'card_id' => $id,
                    'user_id' => $this->userInfo->id,
                ]);
                $this->returnData['msg'] = 'success';
            }
        }

        $this->returnData['code'] = 1;
        $this->returnApiData();
    }

    /**
     * 添加浏览记录
     * @param int $id   新闻ID
     */
    public function setViewHistory($id)
    {
        (new UserCardHistory())->save([
            'card_id' => $id,
            'user_id' => $this->userInfo->id,
            'view_time' => $this->params['view_time'],
        ]);
    }

    public function hasSupport($id)
    {
        $this->returnData['code'] = 1;
        $list = (new UserCardSupport)->where([
            'card_id' => $id,
            'user_id' => $this->userInfo->id,
        ])->select();
        $this->returnData['data'] = (bool)count($list);
        $this->returnApiData('success');
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
